### ISSUE TITLE
Sort order in "Edit server list" not saved

### ISSUE THREAD

**Issue by pljones** [softins/jamulus-web#37]
If I try to move the last entry in the list up and hit Done, the change isn't saved.
Before
![image](https://github.com/softins/jamulus-web/assets/1549463/8471f126-6416-49d6-8f7d-89bb9099ecab)
After edit
![image](https://github.com/softins/jamulus-web/assets/1549463/6e68ceb3-0d75-4571-8663-319a2c1a192f)
Click done.  Go back into edit
![image](https://github.com/softins/jamulus-web/assets/1549463/da3bf321-d8a5-40fd-b9dc-43edb62dad02)
Looks okay... but wait!  Hit Ctrl-F5 (in Firefox) to force a cache cleared refresh.
![image](https://github.com/softins/jamulus-web/assets/1549463/6df1772c-bdac-47b8-a719-45e57c88529c)
Its not been saved after all.

**Comment by softins** [comment]
That was an oversight. The `moveUp()` and `moveDown()` actions were not saving the list to `localStorage`.

Fixed now - please confirm and close if ok.

**Comment by pljones** [comment]
Confirmed, thanks!
