### ISSUE TITLE
Add "Export to..." and "Import from..." options (JSON?)

### ISSUE THREAD

**Issue by pljones** [softins/jamulus-web#38]
It would be nice if you could save your host list.

This would mean
1. I could back up in case of browser local storage corruption
2. Share the same settings on multiple devices

**Comment by softins** [comment]
I've just added that functionality to the live version of [Jamulus Explorer](https://explorer.jamulus.io). Please let me know of any issues.

**Comment by softins** [comment]
Closing as completed
