### ISSUE TITLE
Split Clients into On and Capacity for sorting

### ISSUE THREAD

**Issue by ve3meo** [softins/jamulus-web#6]
Just a suggestion. The Clients column is in the format n/N where n is the number of connections and N is the server capacity. When sorting on the column, it sorts on N. It would be convenient if the column was split into 2 columns n and N so that it is possible to sort on n.

**Comment by softins** [comment]
This is a reasonable idea. I'll have a look at doing that soon.

I recognise your Github username as a Canadian ham radio callsign. I'm G4CJO, but I haven't been on the air for decades.

**Comment by ve3meo** [comment]
Me neither! I've got valve gear mouldering in boxes in the basement.
