### ISSUE TITLE
Make Jamulus explorer accessible via second domain (https://explorer.jamulus.io)

### ISSUE THREAD

**Issue by ann0see** [softins/jamulus-web#8]
Hi @softins,

Since the jamulus project now has the official domain jamulus.io in my opinion it would be great if the Jamulus explorer would also be accessible via explorer.jamulus.io (directly, not via a http redirect). @gilgongo is in charge of the domain and he could create dns records I think. What do you both think about this? It would give this project a more official feeling.

Furthermore encryption (https) would be great.

**Comment by softins** [comment]
I think that is a good idea. I have updated my virtual server to accept `explorer.jamulus.io` directly as a site alias, and also updated the frontend to use the same hostname to talk to the backend, as the one it was called with: 353d2a1ae60716fda293368d5cc00e91cda14183

So if @gilgongo would like to add either of these two DNS records (but not both), it will just work:
* CNAME record pointing to `jamulus.softins.co.uk.`
* A record pointing to `80.85.86.7`

The CNAME would be more flexible, just in case I move the site to another box (I have no plans to).

I'll sort out https using Let's Encrypt as a separate exercise.

BTW, I don't recognise the name ann0see - do I know you outside of Github (e.g. Jamulus/Facebook)?

**Comment by ann0see** [comment]
No, you will not know me from Facebook (since I'm not active there). Furthermore I usually use an other name in Jamulus (which I don't want to publish here).

**Comment by ann0see** [comment]
> So if @gilgongo would like to add either of these two DNS records (but not both), it will just work:

Yes, let's wait for him!

**Comment by gilgongo** [comment]
Sorry, didn't see this. Shall we put it on explore.jamulus.io? I can use a CNAME.

**Comment by ann0see** [comment]
Yes. That would be great

**Comment by softins** [comment]
Great, that now seems to be working. Thank you @gilgongo! I'll get the https cert sorted out soon.

**Comment by ann0see** [comment]
Yes. Looks good now. I wonder what we should do with [canonical URLs](https://en.m.wikipedia.org/wiki/Canonical_link_element). Take explorer.jamulus.io as main one?

**Comment by gilgongo** [comment]
Not sure I understand. All our content is on https://jamulus.io (and www doesn't work), and there's no duplicate content on explorer.jamulus.io so we don't need to bother with marking anything as canonical do we?

**Comment by softins** [comment]
I think @ann0see just meant using explorer.jamulus.io as the preferred URL, rather than jamulus.softins.co.uk, which I think is reasonable, although both will continue to work.

Once I'm confident DNS has propagated to everywhere, I'll add a Let's Encrypt cert for https.

**Comment by ann0see** [comment]
> I think @ann0see just meant using explorer.jamulus.io as the preferred URL, rather than jamulus.softins.co.uk, which I think is reasonable, although both will continue to work.

Exactly. Not sure if we use explorer.jamulus.io as main url since softins would have to ask gilgongo for changes in DNS (although I don't think this would happen often) but of course, explorer.jamulus.io is more accessible.

**Comment by gilgongo** [comment]
Oh I see - hm. So I _guess_ this begs the question: should we have a) a link to the Jamulus home page on the explorer page, and b) some text about Jamulus being used for jamming, rehearsing etc.?

**Comment by softins** [comment]
> Exactly. Not sure if we use explorer.jamulus.io as main url since softins would have to ask gilgongo for changes in DNS 

This is no problem, as explorer.jamulus.io has been set up as a CNAME pointing to my own domain jamulus.softins.co.uk. So if I needed to move the server (unlikely), I would just need to update my own record and it would just work.

**Comment by softins** [comment]
> Oh I see - hm. So I _guess_ this begs the question: should we have a) a link to the Jamulus home page on the explorer page, and b) some text about Jamulus being used for jamming, rehearsing etc.?

Maybe, but people aren't going to find the page independently, so visitors likely know all about Jamulus anyway, having come either from jamulus.io or a Facebook group. I have in mind to redesign the page layout sometime, so perhaps will consider it then.

**Comment by gilgongo** [comment]
OK sure. Worth bearing in my that in the unlikely event that somebody linked to explorer.jamulus.io from a site that ranked well for something like "jamming" or "band rehearsals", then I think having some blurbage about Jamulus on that page would also help (albeit marginally - the link would be nine tenths of the value). We have a separate project going on (the "Knowledge Base") which is designed to attract backlinks, but very little bit helps if we're to get out of almost total Google obscurity :-)

**Comment by softins** [comment]
OK, so now the three URLs http://jamulus.softins.co.uk, https://jamulus.softins.co.uk and http://explorer.jamulus.io will all redirect immediately to https://explorer.jamulus.io

And I have added a small note to the footer with a link to https://jamulus.io

**Comment by ann0see** [comment]
Great!

**Comment by ann0see** [comment]
Thanks again! Can we close this now?

**Comment by softins** [comment]
> Thanks again! Can we close this now?

Sure, I'll do that now.
